language: php

sudo: false

branches:
  only:
    - master

cache:
  directories:
    - $HOME/.composer/cache

php:
  - 5.6
  - 7.0
  - 7.1
  - nightly
  - hhvm

env:
    - SYMFONY_VERSION=2.8.*
    - SYMFONY_VERSION=3.0.*
    - SYMFONY_VERSION=3.1.*
    - SYMFONY_VERSION=3.2.*

before_install:
  - if [[ $TRAVIS_PHP_VERSION != 'hhvm' ]]; then phpenv config-rm xdebug.ini; fi
  - composer self-update

install: composer update $COMPOSER_FLAGS --prefer-dist

before_script: composer require --update-with-dependencies symfony/framework-bundle:${SYMFONY_VERSION}

script: ./vendor/bin/phpunit -c .

matrix:
  fast_finish: true
  allow_failures:
    - php: nightly
    - php: hhvm
